# Generated by Django 5.2.5 on 2025-08-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('partner_organization', models.CharField(blank=True, max_length=255, null=True)),
                ('facility_type', models.CharField(choices=[('Lab', 'Lab'), ('Workshop', 'Workshop'), ('Testing Center', 'Testing Center')], max_length=100)),
                ('capabilities', models.TextField(help_text='E.g. CNC, PCB fabrication, materials testing')),
            ],
        ),
    ]
