# Generated by Django 5.2.5 on 2025-08-26 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('artifact', models.FileField(blank=True, null=True, upload_to='outcomes/')),
                ('outcome_type', models.CharField(choices=[('CAD', 'CAD'), ('PCB', 'PCB'), ('Prototype', 'Prototype'), ('Report', 'Report'), ('Business Plan', 'Business Plan')], max_length=50)),
                ('quality_certification', models.CharField(blank=True, max_length=255, null=True)),
                ('commercialization_status', models.CharField(blank=True, choices=[('Demoed', 'Demoed'), ('Market Linked', 'Market Linked'), ('Launched', 'Launched')], max_length=100, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='projects.project')),
            ],
        ),
    ]
